let data = {
    Generation_1: { 'Bug' : 14 ,
    'Dragon' : 3 ,
    'Electric' : 9 ,
    'Fairy' : 2 ,
    'Fighting' : 7 ,
    'Fire' : 14 ,
    'Ghost' : 4 ,
    'Grass' : 13 ,
    'Ground' : 8 ,
    'Ice' : 2 ,
    'Normal' : 24 ,
    'Poison' : 14 ,
    'Psychic' : 11 ,
    'Rock' : 10 ,
    'Water' : 31 },
       
    Generation_2: { 'Bug' : 12 ,
    'Dark' : 6 ,
    'Electric' : 7 ,
    'Fairy' : 5 ,
    'Fighting' : 2 ,
    'Fire' : 8 ,
    'Ghost' : 1 ,
    'Grass' : 9 ,
    'Ground' : 3 ,
    'Ice' : 4 ,
    'Normal' : 15 ,
    'Poison' : 1 ,
    'Psychic' : 7 ,
    'Rock' : 5 ,
    'Steel' : 3 ,
    'Water' : 18 },
       
    Generation_3: { 'Bug' : 12 ,
    'Dark' : 6 ,
    'Dragon' : 12 ,
    'Electric' : 5 ,
    'Fighting' : 5 ,
    'Fire' : 8 ,
    'Ghost' : 5 ,
    'Grass' : 13 ,
    'Ground' : 7 ,
    'Ice' : 7 ,
    'Normal' : 18 ,
    'Poison' : 3 ,
    'Psychic' : 12 ,
    'Rock' : 8 ,
    'Steel' : 12 ,
    'Water' : 27 },
       
    Generation_4: { 'Bug' : 10 ,
    'Dark' : 3 ,
    'Dragon' : 4 ,
    'Electric' : 12 ,
    'Fairy' : 1 ,
    'Fighting' : 3 ,
    'Fire' : 5 ,
    'Ghost' : 7 ,
    'Grass' : 15 ,
    'Ground' : 4 ,
    'Ice' : 3 ,
    'Normal' : 18 ,
    'Poison' : 6 ,
    'Psychic' : 8 ,
    'Rock' : 6 ,
    'Steel' : 3 ,
    'Water' : 13 },
       
    Generation_5: { 'Bug' : 18 ,
    'Dark' : 13 ,
    'Dragon' : 9 ,
    'Electric' : 8 ,
    'Fighting' : 7 ,
    'Fire' : 9 ,
    'Flying' : 2 ,
    'Ghost' : 5 ,
    'Grass' : 15 ,
    'Ground' : 10 ,
    'Ice' : 6 ,
    'Normal' : 19 ,
    'Poison' : 2 ,
    'Psychic' : 14 ,
    'Rock' : 6 ,
    'Steel' : 4 ,
    'Water' : 18 },
       
    Generation_6: { 'Bug' : 3 ,
    'Dark' : 3 ,
    'Dragon' : 4 ,
    'Electric' : 3 ,
    'Fairy' : 9 ,
    'Fighting' : 3 ,
    'Fire' : 8 ,
    'Flying' : 2 ,
    'Ghost' : 10 ,
    'Grass' : 5 ,
    'Ice' : 2 ,
    'Normal' : 4 ,
    'Poison' : 2 ,
    'Psychic' : 5 ,
    'Rock' : 9 ,
    'Steel' : 5 ,
    'Water' : 5 }   
};
